data: {train_data: /iopsstor/scratch/cscs/mrohania/datasets/DailyTalkCog/dailytalk_cog.jsonl, eval_data: "", shuffle: true}
moshi_paths: {hf_repo_id: "kyutai/moshiko-pytorch-bf16"}
full_finetuning: false
lora: {enable: true, rank: 96, scaling: 2., ft_embed: true}
first_codebook_weight_multiplier: 100.
text_padding_weight: .5
duration_sec: 100
batch_size: 4
max_steps: 400
gradient_checkpointing: true
optim: {lr: 3e-6, weight_decay: 0.1, pct_start: 0.05}
seed: 0
log_freq: 1
do_eval: false
do_ckpt: true
ckpt_freq: 100
save_adapters: true
run_dir: /iopsstor/scratch/cscs/mrohania/moshi_runs/S_cog
